update the new path to main.js
I got this error and found out that the path to main.js has been changed.
```
Error: Cannot find module '/Users/snowflake/.emacs.d/.local/etc/dap-extension/vscode/rebornix.Ruby/extension/out/debugger/main.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```